name: Compress images
on: 
   push:
     paths:
      - '**.jpg'
      - '**.png'
      - '**.webp'
- name: Image Resizer Action
  uses: sharadcodes/img-resizer@v1.0
  with:
    image-folder: 'my_images' # This is a Required field & this folder has original images
    new-resolution: '150x150' # This is Required field
    output-folder: "/assets/thumbnails" # This is Required field & this folder will be used to store resized images
