# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Image Resizer Action
        uses: sharadcodes/img-resizer@v1.0
        with:
          image-folder: '/assets' # This is a Required field & this folder has original images
          new-resolution: '400x200' # This is Required field
          output-folder: "/assets/thumbs" # This is Required field & this folder will be used to
